### ISSUE TITLE
follow the readme document， ipv6 cmd error

### ISSUE THREAD

**Issue by NowAnti** [nicholas-opensource/OpenWrt-Autobuild#10]
OpenWrt 21.02.0-rc1, r16046-59980f7aaf
 -----------------------------------------------------
root@OpenWrt:~# uci del dhcp.@dnsmasq[0].rebind_protection='1'
uci: Entry not found

**Comment by nicholas-opensource** [comment]
Before:

![3CBE2354-7DBE-4A90-BD72-A105ECDE88B6](https://user-images.githubusercontent.com/44309749/117578495-f52fda80-b131-11eb-92ae-6f712dcc9765.jpeg)

After:

![83D81F88-C200-46CC-9D9C-2E4F059EA445](https://user-images.githubusercontent.com/44309749/117578503-07117d80-b132-11eb-9b36-f861d4dede70.jpeg)

If your settings do not enable rebind_protection, everything works right
