### ISSUE TITLE
你好,打搅你了，请问一个问题

### ISSUE THREAD

**Issue by 281677160** [nicholas-opensource/OpenWrt-Autobuild#20]
你好，我在LEDE的issues看到你的发言，在那里提问人太多，怕影响不好，所以来这里问一下，我前几天给封了一个仓库，我也不知道什么原因，我看到你提到仓库有违规的问题，所以来问问，我仓库是什么原因给封的，这样可以避免下次再封
https://github.com/281677160/build-actions 这个是我的新仓库，跟给封了的仓库是一模一样的，请问可以帮我看看是那里违规了吗？感谢！
不好意思哈，我不懂英文，我看你发言都是英文的，翻译过来还是能看懂的，不过我不知道能不能看明白我的意思

**Comment by nicholas-opensource** [comment]
首先，我会中文。其次他的仓库有很多抄袭，和非常复杂的使用GNU GPL代码的问题。GPL是可包容MIT的，只要您没有使用包含GPL使用的代码，一切都是好的。

**Comment by 281677160** [comment]
感谢您的回复，其实我真不知道什么原因，就前几天的事情，给封了一个仓库




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nicholas-opensource/OpenWrt-Autobuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月8日(星期天) 凌晨0:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nicholas-opensource/OpenWrt-Autobuild] 你好,打搅你了，请问一个问题 (#20)





 
首先，我会中文。其次他的仓库有很多抄袭，和非常复杂的使用GNU GPL代码的问题。GPL是可包容MIT的，只要您没有使用包含GPL使用的代码，一切都是好的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nicholas-opensource** [comment]
滥用Action也可能被封。如果担心因为协议问题，可以选择使用GPL等协议

**Comment by 281677160** [comment]
非常感谢您，那天我就修改README.md文件，一边修改，一边保存，改着改着就收到邮件，封仓库了，我就连拉取我仓库的人也全部封了，大概是几十人吧，我了解下GPL协议，真的非常感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nicholas-opensource/OpenWrt-Autobuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月8日(星期天) 凌晨0:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nicholas-opensource/OpenWrt-Autobuild] 你好,打搅你了，请问一个问题 (#20)





 
滥用Action也可能被封。如果担心因为协议问题，可以选择使用GPL等协议
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
