### ISSUE TITLE
SSH 和 ShellClash 遇到问题

### ISSUE THREAD

**Issue by coltchu** [nicholas-opensource/OpenWrt-Autobuild#33]
1. 从上一个版本升级到 v22.03.1 或是刷新固件都不能连接 SSH，重启路由器之后可以解决问题。
2. 安装 ShellClash 很不稳定，一会儿就掉线了，需要重启 ShellClash 才能解决问题。

我就降级回 v21.02.3 了，以前的版本都没有遇到这两个问题。

**Comment by nicholas-opensource** [comment]
SSH是预先设置dropbear interface导致的问题，将会去掉这个选择。
ShellClash无日志目前无法解决，个人认为与固件无直接关系，或者是firewall4导致的问题。

**Comment by coltchu** [comment]
感谢！等下一个版本再试试；）

**Comment by RikudouPatrickstar** [comment]
ShellClash 目前还没支持 nftables https://github.com/juewuy/ShellClash/issues/157

**Comment by nicholas-opensource** [comment]
> ShellClash 目前还没支持 nftables [juewuy/ShellClash#157](https://github.com/juewuy/ShellClash/issues/157)

感谢大佬的回复，那这边先关闭issues了，目前v2102分支依然可用，编译出来就是v21.02.5
