### ISSUE TITLE
v我50

### ISSUE THREAD

**Issue by troubadour-hell** [nicholas-opensource/OpenWrt-Autobuild#35]

**Comment by hahaher123** [comment]
follow

**Comment by SuLingGG** [comment]
![IMG_20230504_224045_252](https://user-images.githubusercontent.com/22287562/236241870-6b915f0b-791c-4cbd-a7e4-1db4a30fc421.png)

**Comment by nicholas-opensource** [comment]
合伙打劫，罪加一等！
